### PR TITLE
Full building, parties Chinese translations

### PR DESCRIPTION
**Pull request by huanghongxun**
Now all texts are translated into Chinese for building series.

### CODE REVIEW

**Comment by huanghongxun** [comment]
Following translations will be added once if the construction sectors cost is fixed so I can continue my play acting as China.

**Comment by settintotrieste** [comment]
Thanks! The construction cost should be fixed in the next steam update.

**Comment by lomirus** [comment]
@huanghongxun What do you think of this suggestion?

**Comment by settintotrieste** [comment]
Hi @lomirus and @huanghongxun, I agree with @lomirus's suggestion to change the localisation of France from 法兰西 to 法国.

**Pull request merged**
