### PR TITLE
Middle Eastern Historical Pack

### PR DESCRIPTION
**Pull request by erdemug**
- Minor change on Turkey IG leaders.
- Ideologies localization typo fix
- Historical officers of Turkey, Greece, Syria, Iraq, Lebanon, Persia and Israel
- DNAs of Paul of Greece and Shah Reza are added. 
- Religion fix for Faisal II and President El Khoury

### CODE REVIEW

**Comment by erdemug** [comment]
TBD:
- Officers of other Mideast countries
- Historical IG leaders (might take a while)
- HoS DNAs (maybe a little bit later)
- Laws (will be much later)

**Comment by erdemug** [comment]
- Rulers of Kuwait, Bahrain, Qatar, Trucial States and Cyrenaica are added. (completed)
- Generals of Middle East are added (completed)
- King of Saudi Arabia is fixed.

TBD:
- Historical IG leaders of 16 MidEastern countries.

**Comment by erdemug** [comment]
I've decided to close it as it is. Because, I would like to work on IG leaders in more detail.

**Comment by settintotrieste** [comment]
Thank you!

**Pull request merged**
